#cloud-config
# Hyper-V Optimized Installation
# Optimized for Microsoft Hyper-V with integration services

version: 1

locale: en_US.UTF-8
keyboard:
  layout: us
  variant: ""

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: true
      # Hyper-V synthetic network adapter
      match:
        driver: hv_netvsc

storage:
  layout:
    name: lvm

identity:
  hostname: hyperv-ubuntu
  username: hvadmin
  realname: "Hyper-V Administrator"
  password: "$6$rounds=4096$VTqez1x6$.N8FgLQRt3HvGxU8JQV1kxF9Y5TmVxLB9KttZFqH4tP1YqJHhGfYdxYvRXGfrLjQQrkyY5hBSZvNqXHKZNbDd/"

ssh:
  install-server: true
  allow-pw: true

packages:
  # Hyper-V specific
  - linux-virtual
  - linux-cloud-tools-virtual
  - linux-tools-virtual
  
  # Integration services
  - hyperv-daemons
  
  # Performance tools
  - tuned
  - irqbalance
  
  # Monitoring
  - htop
  - iotop
  - sysstat
  
  # Basic tools
  - vim
  - curl
  - wget
  - tmux

package_update: true
package_upgrade: true
timezone: UTC

late-commands:
  # Optimize for Hyper-V
  - |
    cat <<EOL > /target/etc/sysctl.d/99-hyperv.conf
    # Hyper-V optimizations
    vm.swappiness = 10
    vm.dirty_ratio = 15
    vm.dirty_background_ratio = 5
    
    # Network optimizations
    net.core.rmem_max = 134217728
    net.core.wmem_max = 134217728
    net.ipv4.tcp_rmem = 4096 87380 134217728
    net.ipv4.tcp_wmem = 4096 65536 134217728
    net.core.netdev_max_backlog = 5000
    EOL
  
  # Configure Hyper-V daemons
  - curtin in-target --target=/target -- systemctl enable hv-kvp-daemon
  - curtin in-target --target=/target -- systemctl enable hv-vss-daemon
  - curtin in-target --target=/target -- systemctl enable hv-fcopy-daemon
  
  # Disable unnecessary services for VM
  - curtin in-target --target=/target -- systemctl disable bluetooth.service || true
  - curtin in-target --target=/target -- systemctl disable cups.service || true
  
  # Configure tuned for virtual guest
  - curtin in-target --target=/target -- tuned-adm profile virtual-guest
  
  # Set up Hyper-V video
  - echo "blacklist hyperv_fb" > /target/etc/modprobe.d/blacklist-hyperv_fb.conf
