#cloud-config
# Database Server Installation
# High-performance database server with PostgreSQL and MySQL/MariaDB

version: 1

locale: en_US.UTF-8
keyboard:
  layout: us
  variant: ""

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: true

storage:
  layout:
    name: lvm

identity:
  hostname: db-server
  username: dbadmin
  realname: "Database Administrator"
  password: "$6$rounds=4096$NQ.MN83i$7z5kIqGFT5B9ULGQ6w5Qvd8gFWH.MZDHcD5aVXEpr8PrTmFMlcVfGVyYLN5dSLyuJ8LfSr.mYH5ekAYqVxTGH."

ssh:
  install-server: true
  allow-pw: true

packages:
  # PostgreSQL
  - postgresql
  - postgresql-contrib
  - postgresql-client
  - postgresql-doc
  - postgresql-plpython3-14
  - postgresql-plperl-14
  
  # MySQL/MariaDB
  - mariadb-server
  - mariadb-client
  - mariadb-backup
  - mariadb-plugin-rocksdb
  
  # NoSQL
  - redis-server
  - redis-tools
  - mongodb-org
  
  # Performance and backup
  - percona-toolkit
  - mydumper
  - pgbackrest
  - barman
  - wal-g
  
  # Monitoring
  - prometheus-postgres-exporter
  - prometheus-mysqld-exporter
  - pg-activity
  - mytop
  
  # Utilities
  - htop
  - iotop
  - ncdu
  - tmux
  - vim
  - git

package_update: true
package_upgrade: true
timezone: UTC

late-commands:
  # Configure PostgreSQL for performance
  - |
    cat <<EOL > /target/etc/postgresql/14/main/conf.d/99-performance.conf
    # Memory
    shared_buffers = 4GB
    effective_cache_size = 12GB
    work_mem = 128MB
    maintenance_work_mem = 1GB
    
    # Checkpoints
    checkpoint_segments = 32
    checkpoint_completion_target = 0.9
    
    # Write ahead log
    wal_buffers = 16MB
    wal_level = replica
    max_wal_senders = 3
    
    # Query tuning
    random_page_cost = 1.1
    effective_io_concurrency = 200
    
    # Logging
    log_statement = 'mod'
    log_duration = on
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d '
    EOL
  
  # Configure MariaDB for performance
  - |
    cat <<EOL > /target/etc/mysql/mariadb.conf.d/99-performance.cnf
    [mysqld]
    # InnoDB
    innodb_buffer_pool_size = 4G
    innodb_log_file_size = 1G
    innodb_flush_method = O_DIRECT
    innodb_file_per_table = 1
    innodb_stats_on_metadata = 0
    
    # MyISAM
    key_buffer_size = 512M
    
    # Query cache
    query_cache_type = 1
    query_cache_size = 128M
    
    # Connections
    max_connections = 500
    thread_cache_size = 50
    
    # Logging
    slow_query_log = 1
    long_query_time = 1
    EOL
  
  # Configure Redis
  - |
    cat <<EOL >> /target/etc/redis/redis.conf
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Memory
    maxmemory 2gb
    maxmemory-policy allkeys-lru
    
    # Performance
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    EOL
  
  # Firewall
  - curtin in-target --target=/target -- ufw --force enable
  - curtin in-target --target=/target -- ufw allow ssh
  - curtin in-target --target=/target -- ufw allow 5432/tcp comment 'PostgreSQL'
  - curtin in-target --target=/target -- ufw allow 3306/tcp comment 'MySQL/MariaDB'
  - curtin in-target --target=/target -- ufw allow 6379/tcp comment 'Redis'
  
  # Create backup directories
  - curtin in-target --target=/target -- mkdir -p /var/backups/postgresql
  - curtin in-target --target=/target -- mkdir -p /var/backups/mysql
  
  # Enable services
  - curtin in-target --target=/target -- systemctl enable postgresql
  - curtin in-target --target=/target -- systemctl enable mariadb
  - curtin in-target --target=/target -- systemctl enable redis-server
