#cloud-config
# Ubuntu Base Autoinstall Configuration
# This is the minimal configuration required for an unattended Ubuntu Server installation

version: 1

# Basic locale and keyboard settings
locale: en_US.UTF-8
keyboard:
  layout: us
  variant: ""

# Network configuration - DHCP by default
network:
  version: 2
  ethernets:
    # This assumes the first ethernet interface
    # Adjust the interface name based on your hardware
    eth0:
      dhcp4: true
      dhcp6: true

# Storage configuration - use entire disk with LVM
storage:
  layout:
    name: lvm

# User account configuration
# IMPORTANT: Change these values before using
identity:
  hostname: ubuntu-server
  username: ubuntu
  # Password is 'ubuntu' - CHANGE THIS!
  # To generate a new password hash, use:
  # openssl passwd -6 -stdin <<< "your-password"
  password: "$6$rounds=4096$J86aZz0Q$To16RGzWJku0swXC3QmvHpJeTT2gJMcjcqgsV4DtiSq0JT7JZhHGFz7KP0K4X0vDnu281sYdYSmm47Q8kXgtm0"

# SSH server configuration
ssh:
  install-server: true
  allow-pw: true

# Essential packages only
packages:
  - openssh-server
  - curl
  - wget
  - vim
  - htop
  - net-tools

# System updates
package_update: true
package_upgrade: true

# Timezone
timezone: UTC

# Optional: Add your SSH keys here
# late-commands:
#   - echo 'ssh-rsa YOUR_SSH_PUBLIC_KEY user@host' >> /target/home/ubuntu/.ssh/authorized_keys