#cloud-config
# Minimal Ubuntu Server Installation
# Absolute minimum packages for a functional server

version: 1

# Locale and keyboard
locale: en_US.UTF-8
keyboard:
  layout: us
  variant: ""

# Network - DHCP on first interface
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: true

# Storage - Simple LVM layout
storage:
  layout:
    name: lvm

# Identity configuration
identity:
  hostname: ubuntu-minimal
  username: ubuntu
  # Password is 'ubuntu' - CHANGE THIS!
  password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"

# SSH configuration
ssh:
  install-server: true
  allow-pw: true

# Minimal package selection
packages:
  - openssh-server
  - curl
  - wget
  - nano
  - net-tools
  - iputils-ping

# System updates
package_update: true
package_upgrade: false
package_reboot_if_required: false

# Timezone
timezone: UTC

# Disable unnecessary services for minimal install
late-commands:
  - curtin in-target --target=/target -- systemctl disable multipathd.service || true
  - curtin in-target --target=/target -- systemctl disable snapd.service || true  
  - curtin in-target --target=/target -- apt-get remove --purge -y snapd || true
  - echo "Minimal Ubuntu Server" > /target/etc/motd