---
# Configure GitHub Enterprise Actions runners

- name: Include variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - ../vars
      skip: true

- name: Install base packages and dependencies
  include_tasks: install.yml
  tags:
    - github-install
    - github-packages

- name: Apply security hardening
  include_tasks: security.yml
  tags:
    - github-security
    - security

- name: Configure GitHub Actions runners
  include_tasks: configure.yml
  tags:
    - github-configure
    - github-runners

- name: Set up monitoring and logging
  include_tasks: monitoring.yml
  tags:
    - github-monitoring
    - monitoring

- name: Configure cleanup and maintenance
  include_tasks: maintenance.yml
  tags:
    - github-maintenance
    - maintenance