---
# Configure GitHub/Git server (using Gitea as example)

- name: Install required packages
  apt:
    name:
      - nginx
      - postgresql
      - postgresql-contrib
      - git
      - git-lfs
      - redis-server
      - certbot
      - python3-certbot-nginx
    state: present

- name: Create git user
  user:
    name: git
    comment: "Git service user"
    home: /home/git
    shell: /bin/bash

- name: Create Gitea directory
  file:
    path: "{{ item }}"
    state: directory
    owner: git
    group: git
    mode: '0755'
  loop:
    - /var/lib/gitea
    - /var/lib/gitea/custom
    - /var/lib/gitea/data
    - /var/lib/gitea/log
    - /etc/gitea

- name: Download Gitea binary
  get_url:
    url: https://dl.gitea.io/gitea/1.21.3/gitea-1.21.3-linux-amd64
    dest: /usr/local/bin/gitea
    mode: '0755'
    owner: root
    group: root

- name: Create PostgreSQL user for Gitea
  become_user: postgres
  postgresql_user:
    name: gitea
    password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
    encrypted: yes

- name: Create PostgreSQL database for Gitea
  become_user: postgres
  postgresql_db:
    name: gitea
    owner: gitea
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

- name: Create Gitea systemd service
  copy:
    dest: /etc/systemd/system/gitea.service
    content: |
      [Unit]
      Description=Gitea (Git with a cup of tea)
      After=syslog.target
      After=network.target
      After=postgresql.service
      
      [Service]
      Type=simple
      User=git
      Group=git
      WorkingDirectory=/var/lib/gitea/
      ExecStart=/usr/local/bin/gitea web -c /etc/gitea/app.ini
      Restart=always
      Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea
      
      [Install]
      WantedBy=multi-user.target

- name: Configure nginx for Gitea
  copy:
    dest: /etc/nginx/sites-available/gitea
    content: |
      server {
        listen 80;
        server_name github.internal.company.com;
        
        location / {
          proxy_pass http://localhost:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

- name: Enable Gitea nginx site
  file:
    src: /etc/nginx/sites-available/gitea
    dest: /etc/nginx/sites-enabled/gitea
    state: link
  notify: restart nginx

- name: Allow HTTP and HTTPS through firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 443
    - 22  # Git SSH

- name: Start and enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop:
    - postgresql
    - redis-server
    - gitea
    - nginx

# Configure Git LFS
- name: Initialize Git LFS
  command: git lfs install --system
  args:
    creates: /etc/gitconfig

# Backup configuration
- name: Create backup script
  copy:
    dest: /usr/local/bin/backup-gitea.sh
    mode: '0755'
    content: |
      #!/bin/bash
      BACKUP_DIR="/var/backups/gitea"
      mkdir -p $BACKUP_DIR
      
      # Backup database
      sudo -u postgres pg_dump gitea > $BACKUP_DIR/gitea-db-$(date +%Y%m%d).sql
      
      # Backup data directory
      tar czf $BACKUP_DIR/gitea-data-$(date +%Y%m%d).tar.gz /var/lib/gitea/
      
      # Keep only last 7 days
      find $BACKUP_DIR -name "*.sql" -mtime +7 -delete
      find $BACKUP_DIR -name "*.tar.gz" -mtime +7 -delete

- name: Schedule daily backups
  cron:
    name: "Gitea backup"
    hour: "2"
    minute: "0"
    job: "/usr/local/bin/backup-gitea.sh"
    user: root

